apiVersion: storage.cloud.atomix.io/v1beta1
kind: RaftStorageClass
metadata:
    name: {{ .Release.Name }}
    labels:
        app: {{ .Release.Name }}
spec:
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.replicas }}
